from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from msagent.core.contracts.adapter_requests import (
    EvaluationAdapterRequest,
    LocateAdapterRequest,
    QueryUnderstandingAdapterRequest,
    SegmentAdapterRequest,
)
from msagent.core.contracts.common import ArtifactKind
from msagent.core.contracts.types import (
    EvaluationIssue,
    EvaluationResult,
    EvaluationVerdict,
    FailureType,
    ImplicitnessLevel,
    NormalizedBox,
    PointHint,
    ProposalBridgeHint,
    ProposalCandidate,
    ProposalResult,
    ProposalRoute,
    ProposalStatus,
    QueryBridgeHint,
    QueryUnderstandingResult,
    ReferentNumber,
    RelationCue,
    RouteHint,
    SegmentationCandidate,
    SegmentationResult,
    SegmentationStatus,
    SpatialCue,
    TargetType,
)
from msagent.infra.adapters import ArtifactStore, LLMAdapter, LocatorAdapter, SAMAdapter
from msagent.infra.local_artifact_store import LocalFileArtifactStore
from msagent.infra.mask_artifact import MaskArtifact


@dataclass(slots=True)
class DeterministicLLMAdapter(LLMAdapter):
    """稳定、可测试的规则化 LLM 替身。"""

    evaluation_verdict_sequence: tuple[EvaluationVerdict, ...] = (
        EvaluationVerdict.ACCEPT,
    )
    evaluation_counter: int = 0

    def run_query_understanding(
        self, request: QueryUnderstandingAdapterRequest
    ) -> QueryUnderstandingResult:
        normalized_query = request.raw_query.strip()
        return QueryUnderstandingResult(
            understanding_id=f"{request.task_id}-understanding",
            normalized_query=normalized_query,
            target_summary=f"Target inferred from query: {normalized_query}",
            target_type=TargetType.OBJECT,
            implicitness=ImplicitnessLevel.EXPLICIT,
            canonical_referent_text=normalized_query,
            referent_number=ReferentNumber.SINGLE,
            focus_terms=[normalized_query],
            attribute_clues=[normalized_query],
            relation_clues=[
                RelationCue(
                    relation_type="self",
                    anchor_text=normalized_query,
                    cue_text="deterministic relation cue",
                )
            ],
            spatial_clues=[
                SpatialCue(
                    cue_type="center_bias",
                    cue_text="deterministic center prior",
                )
            ],
            route_hints=[
                RouteHint(
                    hint_type="prefer_locate",
                    reason="deterministic adapter defaults to locate route",
                    confidence=1.0,
                )
            ],
            bridge_hints=[
                QueryBridgeHint(
                    hint_type="preserve_raw_query",
                    reason="keep the original text for prompt bridge debugging",
                )
            ],
            confidence=0.95,
            notes=["generated by DeterministicLLMAdapter"],
        )

    def run_evaluation(self, request: EvaluationAdapterRequest) -> EvaluationResult:
        verdict = self.evaluation_verdict_sequence[
            min(self.evaluation_counter, len(self.evaluation_verdict_sequence) - 1)
        ]
        self.evaluation_counter += 1

        primary_candidate = next(
            (
                candidate
                for candidate in request.segmentation.candidates
                if candidate.candidate_id == request.segmentation.primary_candidate_id
            ),
            request.segmentation.candidates[0] if request.segmentation.candidates else None,
        )

        if verdict is EvaluationVerdict.ACCEPT and primary_candidate is not None:
            return EvaluationResult(
                evaluation_id=f"{request.task_id}-evaluation-{self.evaluation_counter}",
                verdict=EvaluationVerdict.ACCEPT,
                summary=(
                    "Deterministic evaluator accepted the primary segmentation candidate "
                    f"for prompt '{request.prompt_package.text_prompts.normalized_text}'."
                ),
                accepted_candidate_id=primary_candidate.candidate_id,
                accepted_mask_ref=primary_candidate.mask_ref,
                confidence=0.98,
            )

        return EvaluationResult(
            evaluation_id=f"{request.task_id}-evaluation-{self.evaluation_counter}",
            verdict=verdict,
            summary="Deterministic evaluator rejected the segmentation candidate.",
            failure_type=FailureType.LOCALIZATION_ERROR,
            confidence=0.66,
            issues=[
                EvaluationIssue(
                    issue_type="deterministic_reject",
                    summary="Configured deterministic verdict rejected the current candidate.",
                    severity="medium",
                )
            ],
            retry_hints=["retry_with_same_route"],
        )


@dataclass(slots=True)
class DeterministicLocatorAdapter(LocatorAdapter):
    """稳定的 locate proposal 测试替身。"""

    def locate(self, request: LocateAdapterRequest) -> ProposalResult:
        candidate = ProposalCandidate(
            candidate_id="locate-candidate-1",
            rank=1,
            confidence=0.91,
            matched_clues=[
                request.understanding.normalized_query,
                *request.understanding.focus_terms,
            ],
            region_box=NormalizedBox(x1=0.2, y1=0.18, x2=0.72, y2=0.84),
            positive_point_hints=[
                PointHint(x=0.42, y=0.45, confidence=0.95, reason="target center"),
                PointHint(x=0.55, y=0.62, confidence=0.87, reason="target support"),
            ],
            negative_point_hints=[
                PointHint(x=0.1, y=0.12, confidence=0.72, reason="background corner"),
                PointHint(x=0.86, y=0.22, confidence=0.7, reason="distractor region"),
            ],
            rationale="Deterministic locate route returns one stable spatial prior.",
            limitations=["single_candidate_only"],
        )
        return ProposalResult(
            proposal_id=f"{request.task_id}-proposal-locate",
            route=ProposalRoute.LOCATE,
            status=ProposalStatus.READY,
            proposal_summary="Deterministic locator produced a single ready candidate.",
            candidates=[candidate],
            primary_candidate_id=candidate.candidate_id,
            matched_text_clues=[request.understanding.normalized_query],
            bridge_hints=[
                ProposalBridgeHint(
                    hint_type="prefer_box_plus_points",
                    reason="deterministic locate route provides box and point priors",
                ),
                ProposalBridgeHint(
                    hint_type="need_negative_points",
                    reason="deterministic candidate includes distractor suppression points",
                ),
            ],
            diagnostics=["generated by DeterministicLocatorAdapter"],
        )


@dataclass(slots=True)
class DeterministicSAMAdapter(SAMAdapter):
    """稳定的分割测试替身。"""

    artifact_store: ArtifactStore = field(kw_only=True)
    mask_width: int = 10
    mask_height: int = 10
    default_box: NormalizedBox = field(
        default_factory=lambda: NormalizedBox(x1=0.25, y1=0.25, x2=0.75, y2=0.75)
    )

    def segment(self, request: SegmentAdapterRequest) -> SegmentationResult:
        resolved_box = self._resolve_active_box(request)
        mask_bitmap = self._build_mask_bitmap(resolved_box)
        mask_payload = MaskArtifact(
            mask_id=f"{request.task_id}-mask-1",
            width=self.mask_width,
            height=self.mask_height,
            active_box=resolved_box,
            mask_bitmap=mask_bitmap,
            active_points=[
                (
                    int(point.x * self.mask_width),
                    int(point.y * self.mask_height),
                )
                for point in request.prompt_package.spatial_prompts.positive_points
            ],
            label="deterministic_mask",
            backend_name=self.backend_name,
        )
        mask_ref = self.artifact_store.save_artifact(ArtifactKind.MASK, mask_payload)
        candidate = SegmentationCandidate(
            candidate_id="segmentation-candidate-1",
            mask_ref=mask_ref,
            score=0.94,
            prompt_summary=request.prompt_package.text_prompts.normalized_text,
            notes=["generated by DeterministicSAMAdapter"],
        )
        return SegmentationResult(
            segmentation_id=f"{request.task_id}-segmentation",
            status=SegmentationStatus.READY,
            result_summary="Deterministic SAM adapter produced one segmentation candidate.",
            candidates=[candidate],
            primary_candidate_id=candidate.candidate_id,
            diagnostics=["deterministic segmentation completed"],
        )

    def _resolve_active_box(self, request: SegmentAdapterRequest) -> NormalizedBox:
        boxes = request.prompt_package.spatial_prompts.boxes
        if boxes:
            first_box = boxes[0]
            return NormalizedBox(
                x1=first_box.x1,
                y1=first_box.y1,
                x2=first_box.x2,
                y2=first_box.y2,
            )

        positive_points = request.prompt_package.spatial_prompts.positive_points
        if positive_points:
            xs = [point.x for point in positive_points]
            ys = [point.y for point in positive_points]
            margin = 0.08
            return NormalizedBox(
                x1=max(0.0, min(xs) - margin),
                y1=max(0.0, min(ys) - margin),
                x2=min(1.0, max(xs) + margin),
                y2=min(1.0, max(ys) + margin),
            )

        return self.default_box

    def _build_mask_bitmap(self, active_box: NormalizedBox) -> list[list[bool]]:
        left = max(0, min(self.mask_width, int(active_box.x1 * self.mask_width)))
        top = max(0, min(self.mask_height, int(active_box.y1 * self.mask_height)))
        right = max(left + 1, min(self.mask_width, int(active_box.x2 * self.mask_width)))
        bottom = max(top + 1, min(self.mask_height, int(active_box.y2 * self.mask_height)))

        bitmap: list[list[bool]] = []
        for y in range(self.mask_height):
            row: list[bool] = []
            for x in range(self.mask_width):
                row.append(left <= x < right and top <= y < bottom)
            bitmap.append(row)
        return bitmap


def make_deterministic_service_adapters(
    artifact_root: str | Path,
) -> tuple[DeterministicLocatorAdapter, DeterministicLLMAdapter, DeterministicSAMAdapter]:
    """Create adapters that share the same on-disk artifact root as an assembly."""
    store = LocalFileArtifactStore(str(artifact_root))
    return (
        DeterministicLocatorAdapter(backend_name="deterministic-locator"),
        DeterministicLLMAdapter(backend_name="deterministic-llm"),
        DeterministicSAMAdapter(
            backend_name="deterministic-sam",
            artifact_store=store,
        ),
    )
